make sidplay use sndio
ok sthen

Written by: Alexandre Ratchov <ratchov@openbsd.org>

diff --git a/audio/sidplay/patches/patch-configure b/audio/sidplay/patches/patch-configure
--- a/audio/sidplay/patches/patch-configure
+++ b/audio/sidplay/patches/patch-configure
@@ -1,12 +1,18 @@
-$OpenBSD$
---- configure.orig	Fri Dec  6 12:50:28 2013
-+++ configure	Fri Dec  6 12:50:38 2013
-@@ -1586,7 +1586,7 @@ EOF
-       { echo "configure: error: libossaudio required, but not found." 1>&2; exit 1; };
-     fi
-        ;;
--  *openbsd*) cat >> confdefs.h <<\EOF
-+  *openbsd* | *bitrig*) cat >> confdefs.h <<\EOF
+$OpenBSD: patch-configure,v 1.3 2014/10/26 15:24:10 ratchov Exp $
+--- configure.orig	Sat Sep 28 20:44:14 2002
++++ configure	Fri Oct 24 15:49:10 2014
+@@ -1590,11 +1590,9 @@ EOF
  #define HAVE_OPENBSD 1
  EOF
+ 
+-    $CP audio/oss/* .
+-    echo "$ac_t""oss" 1>&6
+-    if test -z "$LIBAUDIO"; then
+-      { echo "configure: error: libossaudio required, but not found." 1>&2; exit 1; };
+-    fi
++    $CP audio/sndio/* .
++    LIBAUDIO=-lsndio
++    echo "$ac_t""sndio" 1>&6
+        ;;
+ esac
  
