Mark several failing ports as BROKEN.
Mark games/lgeneral BROKEN

Mark games/openttd as BROKEN.

Patch it so it at least tries to build on bitrig but looks like it
has some disagreement with clang even after that.

Mark games/stone-soup BROKEN.

Mark games/teeworlds BROKEN

Mark games/amoebax BROKEN.

Mark games/blobby BROKEN.

Mark games/bzflag BROKEN

Mark games/sdlroids BROKEN

Mark lang/gcc/4.6 BROKEN

Mark x11/fvwm95 BROKEN

Mark lang/scheme48 BROKEN

diff --git a/games/openttd/patches/patch-config_lib b/games/openttd/patches/patch-config_lib
--- a/games/openttd/patches/patch-config_lib
+++ b/games/openttd/patches/patch-config_lib
@@ -1,7 +1,57 @@
 $OpenBSD: patch-config_lib,v 1.4 2014/12/23 11:32:30 dcoppa Exp $
 Don't build with -O1. The reason they add it is irrevelant to OpenBSD anyway.
---- config.lib.orig	Tue Oct 21 13:36:39 2014
-+++ config.lib	Tue Dec 23 05:05:09 2014
+--- config.lib.orig	Tue Oct 21 14:36:39 2014
++++ config.lib	Thu Feb 19 08:28:41 2015
+@@ -526,10 +526,10 @@ check_params() {
+ 		log 1 " PREPROCESSOR is only available for OSX"
+ 		exit 1
+ 	fi
+-	# OS only allows DETECT, UNIX, OSX, FREEBSD, OPENBSD, MORPHOS, BEOS, HAIKU, SUNOS, CYGWIN, MINGW, OS2, DOS, WINCE, and PSP
+-	if [ -z "`echo $os | egrep '^(DETECT|UNIX|OSX|FREEBSD|OPENBSD|NETBSD|HPUX|MORPHOS|BEOS|HAIKU|SUNOS|CYGWIN|MINGW|OS2|DOS|WINCE|PSP)$'`" ]; then
++	# OS only allows DETECT, UNIX, OSX, FREEBSD, OPENBSD, BITRIG, MORPHOS, BEOS, HAIKU, SUNOS, CYGWIN, MINGW, OS2, DOS, WINCE, and PSP
++	if [ -z "`echo $os | egrep '^(DETECT|UNIX|OSX|FREEBSD|OPENBSD|BITRIG|NETBSD|HPUX|MORPHOS|BEOS|HAIKU|SUNOS|CYGWIN|MINGW|OS2|DOS|WINCE|PSP)$'`" ]; then
+ 		log 1 "configure: error: invalid option --os=$os"
+-		log 1 " Available options are: --os=[DETECT|UNIX|OSX|FREEBSD|OPENBSD|NETBSD|HPUX|MORPHOS|BEOS|HAIKU|SUNOS|CYGWIN|MINGW|OS2|DOS|WINCE|PSP]"
++		log 1 " Available options are: --os=[DETECT|UNIX|OSX|FREEBSD|OPENBSD|BITRIG|NETBSD|HPUX|MORPHOS|BEOS|HAIKU|SUNOS|CYGWIN|MINGW|OS2|DOS|WINCE|PSP]"
+ 		exit 1
+ 	fi
+ 	# cpu_type can be either 32 or 64
+@@ -1054,7 +1054,7 @@ check_params() {
+ 	fi
+ 
+ 	if [ "$doc_dir" = "1" ]; then
+-		if [ "$os" = "UNIX" ] || [ "$os" = "FREEBSD" ] || [ "$os" = "OPENBSD" ] || [ "$os" = "NETBSD" ] || [ "$os" = "HPUX" ] || [ "$os" = "SUNOS" ]; then
++		if [ "$os" = "UNIX" ] || [ "$os" = "FREEBSD" ] || [ "$os" = "OPENBSD" ] [ "$os" = "BITRIG" ] || [ "$os" = "NETBSD" ] || [ "$os" = "HPUX" ] || [ "$os" = "SUNOS" ]; then
+ 			doc_dir="share/doc/openttd"
+ 		else
+ 			doc_dir="$data_dir/docs"
+@@ -1064,7 +1064,7 @@ check_params() {
+ 	fi
+ 
+ 	if [ "$icon_theme_dir" = "1" ]; then
+-		if [ "$os" = "UNIX" ] || [ "$os" = "FREEBSD" ] || [ "$os" = "OPENBSD" ] || [ "$os" = "NETBSD" ] || [ "$os" = "HPUX" ] || [ "$os" = "SUNOS" ]; then
++		if [ "$os" = "UNIX" ] || [ "$os" = "FREEBSD" ] || [ "$os" = "OPENBSD" ] || [ "$os" = "BITRIG" ] || [ "$os" = "NETBSD" ] || [ "$os" = "HPUX" ] || [ "$os" = "SUNOS" ]; then
+ 			icon_theme_dir="share/icons/hicolor"
+ 		else
+ 			icon_theme_dir=""
+@@ -1098,7 +1098,7 @@ check_params() {
+ 
+ 	if [ "$man_dir" = "1" ]; then
+ 		# add manpage on UNIX systems
+-		if [ "$os" = "UNIX" ] || [ "$os" = "FREEBSD" ] || [ "$os" = "OPENBSD" ] || [ "$os" = "NETBSD" ] || [ "$os" = "HPUX" ] || [ "$os" = "SUNOS" ] || [ "$os" = "OSX" ]; then
++		if [ "$os" = "UNIX" ] || [ "$os" = "FREEBSD" ] || [ "$os" = "OPENBSD" ] || [ "$os" = "BITRIG"] || [ "$os" = "NETBSD" ] || [ "$os" = "HPUX" ] || [ "$os" = "SUNOS" ] || [ "$os" = "OSX" ]; then
+ 			man_dir="share/man/man6"
+ 		else
+ 			man_dir=""
+@@ -1109,7 +1109,7 @@ check_params() {
+ 
+ 	if [ "$menu_dir" = "1" ]; then
+ 		# add a freedesktop menu item only for some UNIX systems
+-		if [ "$os" = "UNIX" ] || [ "$os" = "FREEBSD" ] || [ "$os" = "OPENBSD" ] || [ "$os" = "NETBSD" ] || [ "$os" = "HPUX" ] || [ "$os" = "SUNOS" ]; then
++		if [ "$os" = "UNIX" ] || [ "$os" = "FREEBSD" ] || [ "$os" = "OPENBSD" ] || [ "$os" = "BITRIG"] || [ "$os" = "NETBSD" ] || [ "$os" = "HPUX" ] || [ "$os" = "SUNOS" ]; then
+ 			menu_dir="share/applications"
+ 		else
+ 			menu_dir=""
 @@ -1488,7 +1488,7 @@ make_cflags_and_ldflags() {
  		cc_build_is_gcc=`basename "$cc_build" | grep "gcc" &>/dev/null`
  		if [ -n "$cc_build_is_gcc" ]; then
@@ -11,3 +61,75 @@ Don't build with -O1. The reason they add it is irrevelant to OpenBSD anyway.
  		fi
  	fi
  
+@@ -1538,7 +1538,7 @@ make_cflags_and_ldflags() {
+ 		fi
+ 	fi
+ 
+-	if [ "$os" != "CYGWIN" ] && [ "$os" != "HAIKU" ] && [ "$os" != "FREEBSD" ] && [ "$os" != "OPENBSD" ] && [ "$os" != "MINGW" ] && [ "$os" != "MORPHOS" ] && [ "$os" != "OSX" ] && [ "$os" != "DOS" ] && [ "$os" != "WINCE" ] && [ "$os" != "PSP" ] && [ "$os" != "OS2" ]; then
++	if [ "$os" != "CYGWIN" ] && [ "$os" != "HAIKU" ] && [ "$os" != "FREEBSD" ] && [ "$os" != "OPENBSD" ] && [ "$os" != "BITRIG" ] && [ "$os" != "MINGW" ] && [ "$os" != "MORPHOS" ] && [ "$os" != "OSX" ] && [ "$os" != "DOS" ] && [ "$os" != "WINCE" ] && [ "$os" != "PSP" ] && [ "$os" != "OS2" ]; then
+ 		LIBS="$LIBS -lpthread"
+ 	fi
+ 
+@@ -1565,6 +1565,10 @@ make_cflags_and_ldflags() {
+ 		LIBS="$LIBS -pthread"
+ 	fi
+ 
++	if [ "$os" = "BITRIG" ]; then
++		LIBS="$LIBS -pthread"
++	fi
++
+ 	if [ "$os" = "FREEBSD" ]; then
+ 		LIBS="$LIBS -lpthread"
+ 	fi
+@@ -1610,7 +1614,7 @@ make_cflags_and_ldflags() {
+ 	fi
+ 
+ 	# Most targets act like UNIX, just with some additions
+-	if [ "$os" = "BEOS" ] || [ "$os" = "HAIKU" ] || [ "$os" = "OSX" ] || [ "$os" = "MORPHOS" ] || [ "$os" = "FREEBSD" ] || [ "$os" = "OPENBSD" ] || [ "$os" = "NETBSD" ] || [ "$os" = "HPUX" ] || [ "$os" = "SUNOS" ] || [ "$os" = "OS2" ]; then
++	if [ "$os" = "BEOS" ] || [ "$os" = "HAIKU" ] || [ "$os" = "OSX" ] || [ "$os" = "MORPHOS" ] || [ "$os" = "FREEBSD" ] || [ "$os" = "OPENBSD" ] || [ "$os" = "BITRIG"] || [ "$os" = "NETBSD" ] || [ "$os" = "HPUX" ] || [ "$os" = "SUNOS" ] || [ "$os" = "OS2" ]; then
+ 		CFLAGS="$CFLAGS -DUNIX"
+ 	fi
+ 	# And others like Windows
+@@ -2268,7 +2272,7 @@ detect_awk() {
+ 
+ detect_os() {
+ 	if [ "$os" = "DETECT" ]; then
+-		# Detect UNIX, OSX, FREEBSD, OPENBSD, NETBSD, HPUX, MORPHOS, BEOS, SUNOS, CYGWIN, MINGW, OS2, DOS, WINCE, and PSP
++		# Detect UNIX, OSX, FREEBSD, OPENBSD, BITRIG, NETBSD, HPUX, MORPHOS, BEOS, SUNOS, CYGWIN, MINGW, OS2, DOS, WINCE, and PSP
+ 
+ 		# Try first via dumpmachine, then via uname
+ 		os=`echo "$host" | tr '[A-Z]' '[a-z]' | $awk '
+@@ -2276,6 +2280,7 @@ detect_os() {
+ 					/darwin/       { print "OSX";     exit}
+ 					/freebsd/      { print "FREEBSD"; exit}
+ 					/openbsd/      { print "OPENBSD"; exit}
++					/bitrig/       { print "BITRIG"; exit}
+ 					/netbsd/       { print "NETBSD";  exit}
+ 					/hp-ux/        { print "HPUX";    exit}
+ 					/morphos/      { print "MORPHOS"; exit}
+@@ -2297,6 +2302,7 @@ detect_os() {
+ 					/darwin/       { print "OSX";     exit}
+ 					/freebsd/      { print "FREEBSD"; exit}
+ 					/openbsd/      { print "OPENBSD"; exit}
++					/bitrig/       { print "BITRIG"; exit}
+ 					/netbsd/       { print "NETBSD";  exit}
+ 					/hp-ux/        { print "HPUX";    exit}
+ 					/morphos/      { print "MORPHOS"; exit}
+@@ -2313,7 +2319,7 @@ detect_os() {
+ 		if [ -z "$os" ]; then
+ 			log 1 "detecting OS... none detected"
+ 			log 1 "I couldn't detect your OS. Please use --os=OS to force one"
+-			log 1 "Allowed values are: UNIX, OSX, FREEBSD, OPENBSD, NETBSD, MORPHOS, HPUX, BEOS, HAIKU, SUNOS, CYGWIN, MINGW, OS2, DOS, WINCE, and PSP"
++			log 1 "Allowed values are: UNIX, OSX, FREEBSD, OPENBSD, BITRIG, NETBSD, MORPHOS, HPUX, BEOS, HAIKU, SUNOS, CYGWIN, MINGW, OS2, DOS, WINCE, and PSP"
+ 			exit 1
+ 		fi
+ 
+@@ -3592,7 +3598,7 @@ showhelp() {
+ 	echo "  --awk=AWK                      the awk to use in configure [awk]"
+ 	echo "  --lipo=LIPO                    the lipo to use (OSX ONLY) [HOST-lipo]"
+ 	echo "  --os=OS                        the OS we are compiling for [DETECT]"
+-	echo "                                 DETECT/UNIX/OSX/FREEBSD/OPENBSD/NETBSD/"
++	echo "                                 DETECT/UNIX/OSX/FREEBSD/OPENBSD/BITRIG/NETBSD/"
+ 	echo "                                 MORPHOS/HPUX/BEOS/SUNOS/CYGWIN/MINGW/OS2/"
+ 	echo "                                 DOS/WINCE/PSP/HAIKU"
+ 	echo "  --endian=ENDIAN                set the endian of the HOST (AUTO/LE/BE)"
