Import sendmail-8.14.9 Thanks to matthieu@ for the work done in base, input from at least zhuk@ and sthen@, ok ajacoutot@
Written by: jca <jca@cvs.openbsd.org>

diff --git a/mail/sendmail/files/sendmail-disable b/mail/sendmail/files/sendmail-disable
--- a/mail/sendmail/files/sendmail-disable
+++ b/mail/sendmail/files/sendmail-disable
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $OpenBSD$
+# $OpenBSD: sendmail-disable,v 1.1.1.1 2014/09/16 17:09:31 jca Exp $
 
 if [ ! -f /etc/mailer.conf.pre-sendmail ]; then
     echo "can't find /etc/mailer.conf.pre-sendmail, sendmail not disabled" >&2
@@ -8,10 +8,14 @@ if [ ! -f /etc/mailer.conf.pre-sendmail ]; then
 fi
 
 if [ -f /etc/mailer.conf ]; then
-    mv -f /etc/mailer.conf /etc/mailer.conf.sendmail
-    mv -f /etc/mailer.conf.pre-sendmail /etc/mailer.conf
-    echo "sendmail mailer.conf disabled, old mailer.conf enabled" >&1
+    if mv -f /etc/mailer.conf /etc/mailer.conf.sendmail &&
+	mv -f /etc/mailer.conf.pre-sendmail /etc/mailer.conf; then
+	echo "sendmail mailer.conf disabled, old mailer.conf enabled" >&2
+    else
+	echo "failed to restore old mailer.conf" >&2
+	exit 1
+    fi
 else
-    echo "can't find /etc/mailer.conf, sendmail not disabled" >&1
+    echo "can't find /etc/mailer.conf, sendmail not disabled" >&2
     exit 1
 fi
diff --git a/mail/sendmail/files/sendmail-enable b/mail/sendmail/files/sendmail-enable
--- a/mail/sendmail/files/sendmail-enable
+++ b/mail/sendmail/files/sendmail-enable
@@ -1,24 +1,23 @@
 #!/bin/sh
 #
-# $OpenBSD$
+# $OpenBSD: sendmail-enable,v 1.1.1.1 2014/09/16 17:09:31 jca Exp $
 
 if [ -f /etc/mailer.conf.sendmail ]; then
     if [ -f /etc/mailer.conf ]; then
-        mv -f /etc/mailer.conf /etc/mailer.conf.pre-sendmail
-        echo "old /etc/mailer.conf saved as /etc/mailer.conf.pre-sendmail" >&2
+	if mv -f /etc/mailer.conf /etc/mailer.conf.pre-sendmail; then
+            echo "old /etc/mailer.conf saved as" \
+		"/etc/mailer.conf.pre-sendmail" >&2
+	else
+	    echo "failed to save current mailer.conf" >&2
+	    exit 1
+	fi
     fi
-    mv -f /etc/mailer.conf.sendmail /etc/mailer.conf
-    printf '%s\n'                                                         \
-	"sendmail /etc/mailer.conf enabled"                               \
-        ""                                                                \
-        "NOTE: do not forget to add smtpd_flags=NO to"                    \
-        "      /etc/rc.conf.local to disable smtpd."                      \
-        ""                                                                \
-        "NOTE: do not forget to add esendmail to pkg_scripts in"          \
-        "      /etc/rc.conf.local to start sendmail automatically."       \
-        ""                                                                \
-        "NOTE: do not forget to add the \"sendmail clientmqueue runner\"" \
-        "      in root's crontab." >&2
+    if mv -f /etc/mailer.conf.sendmail /etc/mailer.conf; then
+        echo "sendmail /etc/mailer.conf enabled" >&2
+    else
+	echo "failed to enable sendmail in /etc/mailer.conf" >&2
+	exit 1
+    fi
 else
     echo "can't find /etc/mailer.conf.sendmail, sendmail not enabled" >&2
     exit 1
